import { StyleSheet, Platform } from 'react-native';
import { colors as themeColors, spacing as themeSpacing, radius as themeRadius, fontSize as themeFontSize, getUi } from '../../theme';

type UiColors = ReturnType<typeof getUi>;
type Colors = typeof themeColors;
type Primary = Colors['primary'];
type Spacing = typeof themeSpacing;
type Radius = typeof themeRadius;
type FontSize = typeof themeFontSize;

export const GRID_PADDING = 20;

export function makeDepensesStyles(
  ui: UiColors,
  colors: Colors,
  primary: (Colors)['primary'],
  spacing: Spacing,
  radius: Radius,
  fontSize: FontSize,
  isDark: boolean
) {
  const cardShadow = Platform.select({
    ios: { shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.08, shadowRadius: 8 },
    android: { elevation: 4 },
  });

  return StyleSheet.create({
  container: { flex: 1, backgroundColor: ui.background },
  centered: { justifyContent: 'center', alignItems: 'center', padding: spacing[6] },
  loaderOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: ui.background,
    zIndex: 100,
    justifyContent: 'center',
    alignItems: 'center',
  },
  errorText: {
    marginTop: spacing[3],
    color: ui.textTitle,
    fontSize: fontSize.base,
    textAlign: 'center',
  },
  retryBtn: {
    marginTop: spacing[4],
    paddingVertical: spacing[3],
    paddingHorizontal: spacing[6],
    backgroundColor: primary.main,
    borderRadius: radius.lg,
  },
  retryBtnText: { color: colors.white, fontWeight: '600', fontSize: fontSize.sm },
  scroll: { flex: 1, backgroundColor: 'transparent' },
  scrollContent: { paddingBottom: spacing[4] },
  content: {},
  periodChromeShell: {
    width: '100%',
    borderBottomWidth: StyleSheet.hairlineWidth,
  },
  periodNavRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: spacing[3],
  },
  periodArrowBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: isDark ? 'rgba(255,255,255,0.04)' : 'rgba(15,23,42,0.03)',
    ...Platform.select({
      ios: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.06,
        shadowRadius: 2,
      },
      android: { elevation: 1 },
    }),
  },
  periodArrowBtnDisabled: { opacity: 0.45 },
  periodArrowBtnPressed: { opacity: 0.85 },
  periodCenterPressable: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing[2],
    paddingVertical: spacing[2],
    paddingHorizontal: spacing[3],
    minWidth: 0,
  },
  periodCenterPressablePressed: { opacity: 0.75 },
  periodCenterLabel: {
    fontSize: fontSize.lg,
    fontWeight: '700',
    color: ui.textTitle,
    letterSpacing: -0.3,
  },
  periodTabsHairline: {
    height: StyleSheet.hairlineWidth,
    width: '100%',
  },
  periodTabsRow: {
    flexDirection: 'row',
    alignItems: 'stretch',
  },
  periodTabBtn: {
    flex: 1,
    alignItems: 'center',
    paddingTop: spacing[3],
    paddingBottom: spacing[2],
    borderBottomWidth: 3,
    borderBottomColor: 'transparent',
  },
  periodTabBtnActive: {
    borderBottomColor: primary.light,
  },
  periodTabLabel: {
    fontSize: 11,
    fontWeight: '600',
    color: ui.textSecondary,
    textTransform: 'uppercase',
    letterSpacing: 0.6,
  },
  periodTabLabelActive: {
    fontWeight: '800',
    color: ui.textTitle,
  },
  pickerYearStrip: {
    maxHeight: 44,
    marginBottom: spacing[3],
  },
  pickerYearStripContent: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing[2],
    paddingVertical: spacing[1],
  },
  pickerYearChip: {
    paddingVertical: spacing[2],
    paddingHorizontal: spacing[4],
    borderRadius: radius.full,
    backgroundColor: ui.surfaceMuted,
    borderWidth: 1,
    borderColor: ui.border,
  },
  pickerYearChipActive: {
    backgroundColor: primary.bg,
    borderColor: primary.main,
  },
  pickerYearChipText: {
    fontSize: fontSize.sm,
    fontWeight: '600',
    color: ui.textSecondary,
  },
  pickerYearChipTextActive: {
    color: primary.main,
    fontWeight: '700',
  },
  recurrencesSection: {
    paddingBottom: spacing[6],
  },
  recurrencesBlockTitle: {
    fontSize: fontSize.lg,
    fontWeight: '700',
    color: ui.textTitle,
    marginBottom: spacing[2],
  },
  recurrencesIntro: {
    fontSize: fontSize.sm,
    color: ui.textSecondary,
    lineHeight: 20,
    marginBottom: spacing[5],
  },
  recurrencesSubBlock: { marginBottom: spacing[5] },
  recurrencesSubTitle: {
    fontSize: fontSize.sm,
    fontWeight: '600',
    color: ui.textSecondary,
    marginBottom: spacing[2],
  },
  recurrenceRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: ui.surface,
    borderRadius: radius.lg,
    padding: spacing[3],
    marginBottom: spacing[2],
    borderWidth: 1,
    borderColor: ui.border,
  },
  recurrenceRowIcon: { marginRight: spacing[3] },
  recurrenceRowBody: { flex: 1, minWidth: 0 },
  recurrenceRowTitle: { fontSize: fontSize.base, fontWeight: '600', color: ui.textTitle },
  recurrenceRowMeta: { fontSize: fontSize.xs, color: ui.textSecondary, marginTop: 2 },
  recurrenceRowAmount: { fontSize: fontSize.base, fontWeight: '700', color: primary.main },
  recurrenceRowAmountIncome: { fontSize: fontSize.base, fontWeight: '700', color: '#059669' },
  recurrenceRowRight: {
    alignItems: 'flex-end',
    justifyContent: 'center',
    gap: spacing[1],
  },
  recurrenceDeleteBtn: { padding: spacing[1] },
  recurrenceDeleteBtnPressed: { opacity: 0.65 },
  recurrencesFabRow: {
    flexDirection: 'row',
    gap: spacing[2],
    marginTop: spacing[4],
  },
  recurrencesFabHalf: { flex: 1, marginTop: 0, minWidth: 0 },
  recurrencesFabBtnText: { flexShrink: 1, fontSize: fontSize.sm, textAlign: 'center' },
  recurrencesLoadingWrap: {
    alignItems: 'center',
    paddingVertical: spacing[4],
  },
  projectsCompactHeader: { marginBottom: spacing[3] },
  projectsCompactTitleRow: { flexDirection: 'row', alignItems: 'center', gap: spacing[2] },
  projectsHint: { marginTop: spacing[1], fontSize: fontSize.xs, color: ui.textTertiary },
  projectsList: { gap: spacing[2], marginBottom: spacing[3] },
  projectCard: {
    backgroundColor: ui.surface,
    borderRadius: radius.lg,
    paddingHorizontal: spacing[3],
    paddingVertical: spacing[3],
    borderWidth: 1,
    borderColor: ui.border,
    ...Platform.select({
      ios: { shadowColor: '#000', shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.05, shadowRadius: 6 },
      android: { elevation: 1 },
    }),
  },
  projectCompactTop: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: spacing[2] },
  projectCardTitle: { flex: 1, fontSize: fontSize.sm, fontWeight: '700', color: ui.textTitle },
  projectCardPct: { fontSize: fontSize.xs, fontWeight: '800', color: primary.main },
  projectProgressTrack: {
    width: '100%',
    height: 6,
    borderRadius: 999,
    backgroundColor: ui.surfaceMuted,
    marginTop: spacing[2] - 2,
    overflow: 'hidden',
  },
  projectProgressFill: { height: '100%', backgroundColor: primary.main, borderRadius: 999 },
  projectCompactAmounts: {
    marginTop: spacing[1] + 1,
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: spacing[1],
  },
  projectCompactAmountMain: { fontSize: fontSize.sm, color: ui.textTitle, fontWeight: '700' },
  projectCompactAmountMuted: { fontSize: fontSize.xs, color: ui.textSecondary, fontWeight: '600' },
  projectCompactDot: { fontSize: fontSize.xs, color: ui.textTertiary, marginHorizontal: 2 },
  projectCompactRemaining: { fontSize: fontSize.xs, color: ui.textSecondary },
  projectActionsRow: { flexDirection: 'row', gap: spacing[2], marginTop: spacing[2] },
  projectActionBtn: {
    flex: 1,
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: ui.border,
    paddingVertical: spacing[1] + 2,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: ui.surfaceMuted,
  },
  projectActionBtnPrimary: { backgroundColor: primary.main, borderColor: primary.main },
  projectActionBtnText: { color: colors.white, fontSize: fontSize.xs, fontWeight: '700' },
  projectActionBtnTextSecondary: { color: ui.textTitle, fontSize: fontSize.xs, fontWeight: '700' },
  recurringFlowToggle: {
    flexDirection: 'row',
    gap: spacing[2],
    marginBottom: spacing[2],
  },
  recurringFlowChip: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing[2],
    paddingVertical: spacing[3],
    borderRadius: radius.lg,
    borderWidth: 2,
    borderColor: ui.border,
    backgroundColor: ui.surfaceMuted,
  },
  recurringFlowChipPressed: { opacity: 0.88 },
  recurringFlowChipActiveOut: {
    backgroundColor: primary.main,
    borderColor: primary.main,
  },
  recurringFlowChipActiveIn: {
    backgroundColor: '#059669',
    borderColor: '#059669',
  },
  recurringFlowChipText: {
    fontSize: fontSize.sm,
    fontWeight: '600',
    color: ui.textTitle,
  },
  recurringFlowChipTextActive: {
    color: colors.white,
  },
  recurringCadenceToggle: {
    flexDirection: 'row',
    gap: spacing[2],
    marginBottom: spacing[3],
  },
  recurringCadenceChip: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: spacing[2],
    paddingHorizontal: spacing[1],
    borderRadius: radius.md,
    borderWidth: 2,
    borderColor: ui.border,
    backgroundColor: ui.surfaceMuted,
    minWidth: 0,
  },
  recurringCadenceChipActiveOut: {
    backgroundColor: primary.main,
    borderColor: primary.main,
  },
  recurringCadenceChipActiveIn: {
    backgroundColor: '#059669',
    borderColor: '#059669',
  },
  recurringCadenceChipText: {
    fontSize: fontSize.xs,
    fontWeight: '600',
    color: ui.textTitle,
    textAlign: 'center',
  },
  recurrencesPlaceholder: {
    alignItems: 'center',
    paddingVertical: spacing[8],
    paddingHorizontal: spacing[6],
  },
  recurrencesIconWrap: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: primary.bg,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: spacing[4],
  },
  recurrencesPlaceholderText: {
    fontSize: fontSize.base,
    color: ui.textSecondary,
    textAlign: 'center',
    lineHeight: 22,
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: spacing[5],
  },
  headerTextWrap: { flex: 1, minWidth: 0 },
  screenTitle: { color: ui.textSecondary, fontSize: fontSize.sm, marginBottom: 2 },
  greeting: { color: ui.textPrimary, fontSize: 22, fontWeight: '800' },
  headerAddBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: spacing[2],
    paddingHorizontal: spacing[4],
    borderRadius: radius.lg,
    backgroundColor: primary.main,
    ...Platform.select({
      ios: { shadowColor: primary.main, shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.25, shadowRadius: 8 },
      android: { elevation: 4 },
    }),
  },
  headerAddBtnLabel: { color: colors.white, fontWeight: '700', fontSize: fontSize.sm },
  headerAddBtnPressed: { opacity: 0.9, transform: [{ scale: 0.98 }] },
  periodCard: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: ui.surface,
    borderRadius: radius.xl,
    padding: spacing[4],
    marginBottom: spacing[2],
    ...cardShadow,
    borderWidth: 1,
    borderColor: ui.border,
  },
  periodCardPressed: { opacity: 0.92 },
  periodLeft: { flexDirection: 'row', alignItems: 'center', flex: 1 },
  periodIconWrap: {
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: primary.bg,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: spacing[3],
  },
  periodLabel: { fontSize: fontSize.xs, color: ui.textSecondary, marginBottom: 2 },
  periodValue: { fontSize: fontSize.lg, fontWeight: '700', color: ui.textPrimary },
  periodYearRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
    paddingVertical: spacing[2],
    marginBottom: spacing[5],
  },
  periodYearText: { fontSize: fontSize.sm, color: ui.textSecondary },
  totalHeroCard: {
    backgroundColor: ui.surface,
    borderRadius: radius.xl,
    padding: spacing[5],
    marginBottom: spacing[5],
    alignItems: 'center',
    ...cardShadow,
    borderWidth: 1,
    borderColor: ui.border,
  },
  totalHeroLabel: { fontSize: fontSize.sm, color: ui.textSecondary, marginBottom: spacing[2] },
  totalHeroAmount: { fontSize: 28, fontWeight: '800', color: '#dc2626', letterSpacing: -0.5 },
  totalHeroAmountIncome: { color: '#059669' },
  totalHeroHint: { marginTop: spacing[3], fontSize: fontSize.xs, color: ui.textTertiary, textAlign: 'center' },
  blockTitle: {
    fontSize: fontSize.sm,
    fontWeight: '600',
    color: ui.textSecondary,
    marginBottom: spacing[3],
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  summaryCard: {
    backgroundColor: ui.surface,
    borderRadius: radius.xl,
    padding: spacing[5],
    marginBottom: spacing[5],
    ...cardShadow,
    borderWidth: 1,
    borderColor: ui.border,
  },
  summaryRow: { flexDirection: 'row', alignItems: 'center' },
  summaryIconWrap: {
    width: 48,
    height: 48,
    borderRadius: 14,
    backgroundColor: 'rgba(220,38,38,0.1)',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: spacing[4],
  },
  summaryTextWrap: { flex: 1 },
  summaryLabel: { color: ui.textSecondary, fontSize: fontSize.sm, marginBottom: 4 },
  summaryAmount: { color: '#dc2626', fontSize: 20, fontWeight: '800' },
  section: { marginBottom: spacing[5] },
  sectionHeaderWithIcon: { flexDirection: 'row', alignItems: 'center', marginBottom: 4 },
  sectionIconWrap: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: primary.bg,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: spacing[2],
  },
  sectionTitle: {
    fontSize: fontSize.lg,
    fontWeight: '700',
    color: ui.textTitle,
  },
  sectionSubtitle: { fontSize: fontSize.sm, color: ui.textSecondary, marginBottom: spacing[3] },
  selectorRow: { flexDirection: 'row', gap: spacing[3] },
  selectorBtn: {
    flex: 1,
    backgroundColor: ui.surface,
    borderRadius: radius.xl,
    padding: spacing[4],
    borderWidth: 1,
    borderColor: ui.border,
    ...cardShadow,
  },
  selectorBtnPressed: { opacity: 0.92 },
  selectorLabel: { fontSize: fontSize.xs, color: ui.textSecondary, marginBottom: spacing[1] },
  selectorValueRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  selectorValue: { fontSize: fontSize.lg, fontWeight: '700', color: ui.textPrimary },
  pickerOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.4)',
    justifyContent: 'flex-end',
  },
  pickerCard: {
    backgroundColor: ui.surface,
    borderTopLeftRadius: radius['2xl'],
    borderTopRightRadius: radius['2xl'],
    paddingHorizontal: GRID_PADDING,
    paddingTop: spacing[4],
    paddingBottom: spacing[6] + 40,
    maxHeight: '70%',
  },
  pickerTitle: { fontSize: fontSize.xl, fontWeight: '700', color: ui.textPrimary, marginBottom: spacing[4] },
  pickerScroll: { maxHeight: 320 },
  pickerOption: {
    paddingVertical: spacing[3],
    paddingHorizontal: spacing[4],
    borderRadius: radius.lg,
    marginBottom: spacing[2],
    backgroundColor: ui.surfaceMuted,
  },
  pickerOptionActive: { backgroundColor: ui.primaryTintBg, borderWidth: 1, borderColor: ui.primaryTintBorder },
  pickerOptionDisabled: { opacity: 0.4 },
  pickerOptionText: { fontSize: fontSize.base, color: ui.textTitle },
  pickerOptionTextActive: { fontWeight: '700', color: ui.primaryTintText },
  pickerOptionTextDisabled: { color: ui.textTertiary },
  pickerCloseBtn: {
    marginTop: spacing[4],
    paddingVertical: spacing[3],
    alignItems: 'center',
  },
  pickerCloseText: { fontSize: fontSize.base, fontWeight: '600', color: ui.textSecondary },
  expenseCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: ui.surface,
    borderRadius: radius.lg,
    padding: spacing[4],
    marginBottom: spacing[3],
    ...cardShadow,
    borderWidth: 1,
    borderColor: ui.border,
  },
  expenseCardPressed: { opacity: 0.92 },
  expenseIconWrap: {
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: 'rgba(220,38,38,0.08)',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: spacing[3],
  },
  expenseBody: { flex: 1, minWidth: 0 },
  expenseTitle: { fontSize: fontSize.base, fontWeight: '600', color: ui.textTitle },
  expenseDesc: { fontSize: fontSize.sm, color: ui.textSecondary, marginTop: 2 },
  expenseDate: { fontSize: fontSize.xs, color: ui.textTertiary, marginTop: 4 },
  expenseAmount: {
    fontSize: fontSize.base,
    fontWeight: '700',
    color: '#dc2626',
    marginLeft: spacing[2],
  },
  emptyState: {
    alignItems: 'center',
    paddingVertical: spacing[10],
    backgroundColor: ui.surface,
    borderRadius: radius.xl,
    ...cardShadow,
    borderWidth: 1,
    borderColor: ui.border,
  },
  emptyIconWrap: {
    width: 72,
    height: 72,
    borderRadius: 24,
    backgroundColor: primary.bg,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: spacing[4],
  },
  emptyText: { color: ui.textTitle, fontSize: fontSize.base, fontWeight: '600' },
  emptySub: { marginTop: spacing[2], color: ui.textSecondary, fontSize: fontSize.sm },
  emptyStateIncome: { padding: spacing[6], alignItems: 'center', backgroundColor: 'rgba(5,150,105,0.04)', borderRadius: 12, borderWidth: 1, borderColor: 'rgba(5,150,105,0.15)' },
  emptyIconWrapIncome: { width: 48, height: 48, borderRadius: 24, backgroundColor: 'rgba(5,150,105,0.1)', alignItems: 'center', justifyContent: 'center', marginBottom: spacing[3] },
  emptyTextIncome: { color: ui.textSecondary, fontSize: fontSize.sm },
  incomeTotalRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingVertical: spacing[3], paddingHorizontal: spacing[4], backgroundColor: 'rgba(5,150,105,0.08)', borderRadius: 12, marginBottom: spacing[3] },
  incomeTotalLabel: { fontSize: fontSize.sm, fontWeight: '600', color: ui.textTitle },
  incomeTotalAmount: { fontSize: fontSize.lg, fontWeight: '800', color: '#059669' },
  incomeCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: ui.surface,
    padding: spacing[4],
    borderRadius: 12,
    marginBottom: spacing[2],
    borderWidth: 1,
    borderColor: ui.border,
    ...Platform.select({
      ios: { shadowColor: '#000', shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.04, shadowRadius: 4 },
      android: { elevation: 2 },
    }),
  },
  incomeCardIconWrap: { width: 40, height: 40, borderRadius: 20, backgroundColor: 'rgba(5,150,105,0.12)', alignItems: 'center', justifyContent: 'center', marginRight: spacing[3] },
  incomeCardAmount: { fontSize: fontSize.base, fontWeight: '700', color: '#059669' },
  addBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing[2],
    paddingVertical: spacing[4],
    borderRadius: radius.xl,
    marginTop: spacing[2],
  },
  addBtnExpense: {
    backgroundColor: primary.main,
    ...Platform.select({
      ios: { shadowColor: primary.main, shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.2, shadowRadius: 8 },
      android: { elevation: 4 },
    }),
  },
  addBtnIncomeFab: {
    backgroundColor: '#059669',
    ...Platform.select({
      ios: { shadowColor: '#059669', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.22, shadowRadius: 8 },
      android: { elevation: 4 },
    }),
  },
  addBtnPressed: { opacity: 0.92 },
  addBtnText: { color: colors.white, fontWeight: '700', fontSize: fontSize.base },
  categoryBlock: { marginBottom: spacing[5] },
  categoryHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing[2],
    marginBottom: spacing[3],
    paddingVertical: spacing[2],
    paddingLeft: spacing[2],
    borderLeftWidth: 3,
    borderLeftColor: primary.main,
    borderRadius: 4,
  },
  categoryTitle: { fontSize: fontSize.base, fontWeight: '700', color: ui.textTitle },
  categoriesToggle: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing[2],
    paddingVertical: spacing[3],
    paddingHorizontal: spacing[4],
    marginTop: spacing[2],
    marginBottom: spacing[2],
    backgroundColor: ui.surfaceMuted,
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: ui.border,
  },
  categoriesTogglePressed: { opacity: 0.85 },
  categoryItemsToggle: { marginTop: spacing[2], marginBottom: 0 },
  categoriesToggleText: { fontSize: fontSize.sm, fontWeight: '600', color: primary.main },
  modalOverlay: {
    flex: 1,
    justifyContent: 'flex-end',
  },
  modalBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0,0,0,0.4)',
  },
  modalCard: {
    backgroundColor: ui.surface,
    borderTopLeftRadius: radius['2xl'],
    borderTopRightRadius: radius['2xl'],
    paddingHorizontal: GRID_PADDING,
    paddingBottom: spacing[8] + 40,
    maxHeight: '90%',
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: spacing[4],
    borderBottomWidth: 1,
    borderBottomColor: ui.surfaceMuted,
  },
  modalTitle: { fontSize: fontSize.xl, fontWeight: '700', color: ui.textPrimary },
  modalCloseBtn: { padding: spacing[2] },
  addChoiceWrap: { paddingVertical: spacing[2] },
  addChoiceLabel: {
    fontSize: fontSize.sm,
    color: ui.textSecondary,
    marginBottom: spacing[4],
  },
  addChoiceBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: spacing[4],
    borderRadius: radius.xl,
    marginBottom: spacing[3],
    borderWidth: 2,
  },
  addChoiceBtnPressed: { opacity: 0.9 },
  addChoiceBtnIncome: {
    backgroundColor: 'rgba(5,150,105,0.08)',
    borderColor: 'rgba(5,150,105,0.3)',
  },
  addChoiceBtnExpense: {
    backgroundColor: 'rgba(220,38,38,0.06)',
    borderColor: 'rgba(220,38,38,0.25)',
  },
  addChoiceBtnTextWrap: { flex: 1, marginLeft: spacing[3] },
  addChoiceBtnTitle: {
    fontSize: fontSize.lg,
    fontWeight: '700',
    color: ui.textPrimary,
  },
  addChoiceBtnSub: {
    fontSize: fontSize.xs,
    color: ui.textSecondary,
    marginTop: 2,
  },
  inputLabel: {
    fontSize: fontSize.sm,
    fontWeight: '600',
    color: ui.textTitle,
    marginTop: spacing[4],
    marginBottom: spacing[1],
  },
  input: {
    borderWidth: 1,
    borderColor: ui.border,
    borderRadius: radius.lg,
    paddingHorizontal: spacing[4],
    paddingVertical: spacing[3],
    fontSize: fontSize.base,
    color: ui.textPrimary,
  },
  inputMultiline: { minHeight: 72, textAlignVertical: 'top' },
  datePickPressable: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing[3],
    borderWidth: 1,
    borderColor: ui.border,
    borderRadius: radius.lg,
    paddingHorizontal: spacing[4],
    paddingVertical: spacing[3],
    marginTop: spacing[2],
    backgroundColor: ui.surface,
  },
  datePickPressablePressed: { opacity: 0.88 },
  datePickText: { fontSize: fontSize.base, color: ui.textPrimary, fontWeight: '600' },
  dateIosBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.35)',
    justifyContent: 'flex-end',
  },
  dateIosSheet: {
    backgroundColor: ui.surface,
    borderTopLeftRadius: radius.xl,
    borderTopRightRadius: radius.xl,
    paddingBottom: spacing[6],
    paddingTop: spacing[3],
    borderTopWidth: StyleSheet.hairlineWidth,
    borderColor: ui.border,
  },
  dateIosDoneBtn: {
    marginHorizontal: spacing[4],
    marginTop: spacing[3],
    paddingVertical: spacing[3],
    borderRadius: radius.lg,
    backgroundColor: primary.main,
    alignItems: 'center',
  },
  dateIosDoneText: { color: colors.white, fontWeight: '700', fontSize: fontSize.base },
  categoryGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing[2],
    marginTop: spacing[2],
  },
  categoryChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing[1],
    paddingVertical: spacing[2],
    paddingHorizontal: spacing[3],
    borderRadius: radius.full,
    backgroundColor: ui.surfaceMuted,
    borderWidth: 1,
    borderColor: 'transparent',
  },
  categoryChipActive: {
    backgroundColor: primary.main,
    borderColor: primary.main,
  },
  categoryChipText: { fontSize: fontSize.sm, color: ui.textSecondary },
  categoryChipTextActive: { color: colors.white, fontWeight: '600' },
  checkboxRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing[3],
    marginTop: spacing[4],
    paddingVertical: spacing[2],
  },
  checkboxRowPressed: { opacity: 0.85 },
  checkboxLabel: { flex: 1, fontSize: fontSize.sm, color: ui.textTitle },
  formError: { marginTop: spacing[2], color: '#dc2626', fontSize: fontSize.sm },
  submitBtn: {
    marginTop: spacing[6],
    backgroundColor: primary.main,
    paddingVertical: spacing[3],
    borderRadius: radius.lg,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 48,
  },
  submitBtnDisabled: { opacity: 0.8 },
  submitBtnText: { color: colors.white, fontWeight: '600', fontSize: fontSize.base },
});
}

export type DepensesStyles = ReturnType<typeof makeDepensesStyles>;
